/**
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

pipeline {
  agent {
      label "terraform-exec"
  }
  stages {
    // [START tf-init, tf-validate]
    stage('TF init & validate') {
      when { anyOf {branch "prod";branch "dev";changeRequest() } }
      steps {
        container('terraform') {
          sh '''
	  echo ""
	  echo "*************** TERRAFOM INIT and VALIDATE ******************"
	  echo "******* At environment: ${env} ********"
	  echo "*************************************************"
          echo $JOB_NAME
          cd landing-zone-pipelines/0-bootstrap
	  terraform init || exit 1
	  terraform validate || exit 1
          cd -'''
      }
     }
    }
    // [END tf-init, tf-validate]

    // [START tf-plan]
    stage('TF plan') {
      when { anyOf {branch "prod";branch "dev";changeRequest() } }
      steps {
        container('terraform') {
          sh '''
	  echo ""
	  echo "*************** TERRAFOM PLAN******************"
	  echo "******* At environment: ${env} ********"
	  echo "*************************************************"
          cd landing-zone-pipelines/0-bootstrap
	  terraform plan || exit 1
          cd -'''
        }
      }
    }
    // [END tf-plan]

    // [START tf-apply]
    stage('TF Apply') {
      when { anyOf {branch "prod";branch "dev" } }
      steps {
        container('terraform') {
          sh '''
	  echo ""
	  echo "*************** TERRAFOM APPLY******************"
	  echo "******* At environment: ${env} ********"
	  echo "*************************************************"
          cd landing-zone-pipelines/0-bootstrap
	  terraform apply || exit 1
          cd -'''
      }
    }
  }
  // [END tf-apply]
 }
}
